import sql from "k6/x/sql";
import driver from "k6/x/sql/driver/hdb";

// Pass the connection string with: k6 run -e K6_SQL_HDB_DSN=hdb://... examples/example.js
const db = sql.open(
  driver,
  __ENV.K6_SQL_HDB_DSN || "hdb://HANA_USER:HANA_PASSWORD@HANA_HOST:30015",
);

export function setup() {
  db.exec(`
    CREATE COLUMN TABLE test_table (
      a INT GENERATED BY DEFAULT AS IDENTITY,
      b NVARCHAR(64),
      PRIMARY KEY (a)
    )
  `);
}

export function teardown() {
  db.exec("DROP TABLE test_table");
  db.close();
}

export default function () {
  let result = db.exec("INSERT INTO test_table (b) VALUES (?)", "One");
  console.log(`${result.rowsAffected()} rows inserted`);

  // SAP HANA uses positional '?' placeholders, not '$1', and folds unquoted
  // identifiers to upper case, so the result columns are named A and B.
  let rows = db.query("SELECT a, b FROM test_table WHERE b = ?", "One");
  for (const row of rows) {
    console.log(`key: ${row.A}, value: ${row.B}`);
  }
}
