const db = sql.open(driver, connection);

// SAP HANA has no CREATE TABLE IF NOT EXISTS, so drop any leftover table first.
try {
  db.exec("DROP TABLE test_table");
} catch (_) {
  // the table did not exist, nothing to drop
}

db.exec(`
  CREATE COLUMN TABLE test_table (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name NVARCHAR(64) NOT NULL,
    value NVARCHAR(64),
    PRIMARY KEY (id)
  )
`);

for (let i = 0; i < 5; i++) {
  db.exec("INSERT INTO test_table (name, value) VALUES (?, ?)", "name-" + i, "value-" + i);
}

let all_rows = db.query("SELECT * FROM test_table");
if (all_rows.length != 5) {
  throw new Error("Expected all five rows to be returned; got " + all_rows.length);
}

let one_row = db.query("SELECT * FROM test_table WHERE name = ?", "name-2");
if (one_row.length != 1) {
  throw new Error("Expected single row to be returned; got " + one_row.length);
}

let no_rows = db.query("SELECT * FROM test_table WHERE name = ?", "bogus-name");
if (no_rows.length != 0) {
  throw new Error("Expected no rows to be returned; got " + no_rows.length);
}

db.exec("DROP TABLE test_table");

db.close();
